# Data Preprocessing for Machine Learning
### Dataset: Churn Prediction
### Tools: Python, Pandas, Scikit-learn

In [1]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

## Step 1: Handling Missing Data

In [2]:
df = pd.read_csv('../Data Set For Task/Churn Prdiction Data/churn-bigml-80.csv')

In [3]:
df.shape

(2666, 20)

In [4]:
df.isnull().sum()

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

Since the dataset has no missing values, we manually introduced NaN values 
to practice different imputation techniques:
- Numerical columns filled with **mean**
- Categorical columns filled with **mode**

In [5]:
df_missing = df.copy()

In [6]:
df_missing.loc[10:30, 'Account length'] = np.nan
df_missing.loc[50:70, 'International plan'] = np.nan
df_missing.loc[100:120, 'Total day minutes'] = np.nan

In [7]:
df_missing.isnull().sum()

State                      0
Account length            21
Area code                  0
International plan        21
Voice mail plan            0
Number vmail messages      0
Total day minutes         21
Total day calls            0
Total day charge           0
Total eve minutes          0
Total eve calls            0
Total eve charge           0
Total night minutes        0
Total night calls          0
Total night charge         0
Total intl minutes         0
Total intl calls           0
Total intl charge          0
Customer service calls     0
Churn                      0
dtype: int64

In [8]:
print(df_missing["Account length"].dtype)
print(df_missing['International plan'].dtype)
print(df_missing['Total day minutes'].dtype)

float64
object
float64

In [9]:
df_missing['Account length'] = df_missing['Account length'].fillna(df_missing['Account length'].mean())

In [10]:
df_missing['Total day minutes'] = df_missing['Total day minutes'].fillna(df_missing['Total day minutes'].mean())

In [11]:
df_missing['International plan'] = df_missing['International plan'].fillna(df_missing['International plan'].mode()[0])

In [12]:
df_missing.isnull().sum()

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

## Step 2: Encoding Categorical Variables
Machine learning models only understand numbers, so we convert text columns to numerical values.
- **Label Encoding** is used for State (high cardinality - 51 unique values)
- **One Hot Encoding** is used for International plan and Voice mail plan (binary - Yes/No)

In [13]:
df_missing.select_dtypes(include='object').nunique()

State                 51
International plan     2
Voice mail plan        2
dtype: int64

In [14]:
le = LabelEncoder()
df_missing['State'] = le.fit_transform(df_missing['State'])

In [15]:
df_missing['State'].head()

0    16
1    35
2    31
3    35
4    36
Name: State, dtype: int64

In [16]:
df_missing = pd.get_dummies(df_missing, columns=['International plan', 'Voice mail plan'])

In [17]:
df_missing.head()

,State,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,...,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,International plan_No,International plan_Yes,Voice mail plan_No,Voice mail plan_Yes
0,16,128.0,415,25,265.1,110,45.07,197.4,99,16.78,...,11.01,10.0,3,2.70,1,False,True,False,False,True
1,35,107.0,415,26,161.6,123,27.47,195.5,103,16.62,...,11.45,13.7,3,3.70,1,False,True,False,False,True
2,31,137.0,415,0,243.4,114,41.38,121.2,110,10.30,...,7.32,12.2,5,3.29,0,False,True,False,True,False
3,35,84.0,408,0,299.4,71,50.90,61.9,88,5.26,...,8.86,6.6,7,1.78,2,False,False,True,True,False
4,36,75.0,415,0,166.7,113,28.34,148.3,122,12.61,...,8.41,10.1,3,2.73,3,False,False,True,True,False

Dropping the columns to reduce redundancy

In [18]:
df_missing = df_missing.drop(columns=['International plan_No', 'Voice mail plan_No'])

In [19]:
df_missing = df_missing.rename(columns={
    'International plan_Yes': 'International plan',
    'Voice mail plan_Yes' : 'Voice mail plan'
})

In [20]:
df_missing.columns.tolist()

['State',
 'Account length',
 'Area code',
 'Number vmail messages',
 'Total day minutes',
 'Total day calls',
 'Total day charge',
 'Total eve minutes',
 'Total eve calls',
 'Total eve charge',
 'Total night minutes',
 'Total night calls',
 'Total night charge',
 'Total intl minutes',
 'Total intl calls',
 'Total intl charge',
 'Customer service calls',
 'Churn',
 'International plan',
 'Voice mail plan']

## Step 3: Standardizing Numerical Features
Scaling ensures no feature dominates the model simply because of larger values.
We use **StandardScaler** which transforms each feature to have mean=0 and standard deviation=1.
Columns like State, Area code, and Churn are excluded from scaling.

In [22]:
df_missing.nunique()

State                       51
Account length             206
Area code                    3
Number vmail messages       42
Total day minutes         1490
Total day calls            115
Total day charge          1489
Total eve minutes         1442
Total eve calls            120
Total eve charge          1301
Total night minutes       1444
Total night calls          118
Total night charge         885
Total intl minutes         158
Total intl calls            21
Total intl charge          158
Customer service calls      10
Churn                        2
International plan           2
Voice mail plan              2
dtype: int64

In [23]:
df_missing.dtypes

State                       int64
Account length            float64
Area code                   int64
Number vmail messages       int64
Total day minutes         float64
Total day calls             int64
Total day charge          float64
Total eve minutes         float64
Total eve calls             int64
Total eve charge          float64
Total night minutes       float64
Total night calls           int64
Total night charge        float64
Total intl minutes        float64
Total intl calls            int64
Total intl charge         float64
Customer service calls      int64
Churn                        bool
International plan           bool
Voice mail plan              bool
dtype: object

In [25]:
columns_to_scale = df_missing.select_dtypes(include=['float64','int64']).columns.tolist()
columns_to_exclude = ['State', 'Area code']
columns_to_scale = [cols for cols in columns_to_scale if cols not in columns_to_exclude]

In [26]:
scaler = StandardScaler()
df_missing[columns_to_scale] = scaler.fit_transform(df_missing[columns_to_scale])
df_missing.head()

,State,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,International plan,Voice mail plan
0,16,0.694691,415,1.247508,1.582991,0.484868,1.579942,-0.058619,-0.050781,-0.058445,0.857403,-0.469031,0.856707,-0.085020,-0.597527,-0.085681,-0.429172,False,False,True
1,35,0.160834,415,1.320985,-0.331057,1.135375,-0.330194,-0.095916,0.147654,-0.095397,1.048458,0.149054,1.049293,1.242179,-0.597527,1.242921,-0.429172,False,False,True
2,31,0.923486,415,-0.589414,1.181688,0.685024,1.179465,-1.554439,0.494917,-1.554963,-0.759668,0.200561,-0.758391,0.704125,0.216894,0.698194,-1.191955,False,False,False
3,35,-0.423865,408,-0.589414,2.217308,-1.466653,2.212675,-2.718509,-0.596479,-2.718922,-0.084083,-0.572045,-0.084339,-1.304609,1.031314,-1.307995,0.333610,False,True,False
4,36,-0.652661,415,-0.589414,-0.236742,0.634985,-0.235772,-1.022461,1.090224,-1.021482,-0.281046,1.076181,-0.281303,-0.049150,-0.597527,-0.045823,1.096392,False,True,False

## Step 4: Train Test Split
We split the dataset into 80% training and 20% testing sets.
- **X** contains all features (input)
- **y** contains the target column Churn (output)
- **random_state=42** ensures the same split every time for reproducibility.

In [27]:
x = df_missing.drop(columns=['Churn'])
y= df_missing['Churn']

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

print(x_train.shape)
print(x_test.shape)

(2132, 19)
(534, 19)